/*
* ============================================================================
*  Name     : CFriendDocument from FriendDocument.h
*  Part of  : Friend
*  Created  : 21.07.2006 by 
*  Implementation notes:
*     Initial content was generated by Series 60 Application Wizard.
*  Version  :
*  Copyright: 
* ============================================================================
*/

// INCLUDE FILES
#include "FriendDocument.h"
#include "FriendAppui.h"

// ================= MEMBER FUNCTIONS =======================

// constructor
CFriendDocument::CFriendDocument(CEikApplication& aApp)
: CAknDocument(aApp)    
    {
    }

// destructor
CFriendDocument::~CFriendDocument()
    {
    }

// EPOC default constructor can leave.
void CFriendDocument::ConstructL()
    {
    }

// Two-phased constructor.
CFriendDocument* CFriendDocument::NewL(
        CEikApplication& aApp)     // CFriendApp reference
    {
    CFriendDocument* self = new (ELeave) CFriendDocument( aApp );
    CleanupStack::PushL( self );
    self->ConstructL();
    CleanupStack::Pop();

    return self;
    }
    
// ----------------------------------------------------
// CFriendDocument::CreateAppUiL()
// constructs CFriendAppUi
// ----------------------------------------------------
//
CEikAppUi* CFriendDocument::CreateAppUiL()
    {
    return new (ELeave) CFriendAppUi;
    }

// End of File  
